server:
  port: 8082

# mysql
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/user
    username: root
    password: root
  application:
      name: auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    port: 6379
    host: 192.168.56.10
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
  level:
    com.ken.zshop: debug

github:
  # 客户端ID
  clientId: fb8d4ad33dd96d4b66b3
  # 客户端秘钥
  clientSecret: f9196e2de8f3646d7f2b39cc3a62b67af0a679a1
  # 用户授权地址（返回授权码）
  authorizationUrl: https://github.com/login/oauth/authorize
  # 回调地址，获取access_token
  redirectUrl: http://localhost:8082/auth2/success
  # 认证服务器生成access_token
  accessTokenUrl: https://github.com/login/oauth/access_token
  # 获取用户身份信息
  userInfoUrl: https://api.github.com/user
